### ISSUE TITLE
Unnecessary zooming in some map types

### ISSUE THREAD

**Issue by rosaliechan** [NUKnightLab/StoryMapJS#326] opened 2016-11-21 21:49 UTC
In some map types, like terrain, there is unnecessary zooming. Rather than zooming into the pins, it will keep zooming out.

**Comment by JoeGermuska** [comment] 2016-11-21 21:55
@rosaliechan Can you add a link to a map which demonstrates the issue and steps someone should take to reproduce it?

**Comment by rosaliechan** [comment] 2016-11-22 17:42
@JoeGermuska Here's an example of a storymap that keeps zooming out: https://uploads.knightlab.com/storymapjs/bee7d21309c2e0e8ee7f6efe6d32549a/bungalow-magazine/index.html  Another student in the past has also asked me about this, and I believe it was for the same map type. To fix it, we just switched the map type.  
I tried using terrain to create a map with correct zooming, but was unable to do so.  Even if there is a way to do that, it's not intuitive to the user.

**Comment by rosaliechan** [comment] 2016-11-22 17:46
So looking back at old Slack messages, I had asked Zach about this in the past when a student brought this up to me.  He just said that the terrain map type does not have many zoom levels availalble. I think that's a bug, or at least, it needs to be made clear to the user.

**Comment by JoeGermuska** [comment] 2017-02-06 16:13
duplicate of #338

**Closed by JoeGermuska** 2017-02-06 16:13 UTC
Labels: bug
