### ISSUE TITLE
Allow for different base map per slide

### ISSUE THREAD

**Issue by miloskroulik** [NUKnightLab/StoryMapJS#229] opened 2015-06-07 20:07 UTC
For my use case, it would be very useful to be able to define different base map per slide, because I have to display places on different sides of world, where different base maps offer best quality. The best way to do this would be probably one default value for all slides, which will be used unless there's another in slide settings.

**Comment by JoeGermuska** [comment] 2015-06-08 19:31
This seems like a duplicate of #230

**Closed by JoeGermuska** 2015-06-08 19:31 UTC

**Comment by JoeGermuska** [comment] 2015-06-08 19:51
Not a duplicate of #230. But the comment making that one a WONTFIX applies to this:
> I'm not sure how we would gracefully move the map from one point to another while also changing the base map. There would inevitably be flicker which I think would make for a negative user experience.
